apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: dns-custom
spec:
  desiredState:
    dns-resolver:
      config:
        search:
          - cluster.local
        server:
          - 10.36.64.2
          - 10.36.41.51

