---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argocd-nmstate-manager # Nome descritivo para o Role
rules:
- apiGroups: ["nmstate.io"] # O grupo de API que será utilizado para criar objetos do nmstate
  resources: ["*"]
  verbs: ["*"] 
- apiGroups: ["batch"] # O grupo de API que será utilizado para criar o job de limpeza
  resources: ["jobs"]
  verbs: ["*"] 
- apiGroups: [""] # O grupo de API para ServiceAccounts é vazio ("")
  resources: ["serviceaccounts"] 
  verbs: ["create", "get", "list", "watch", "update", "patch", "delete"] # Ou apenas "create" e "update" se preferir

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argocd-nmstate-binding # Nome descritivo para o Binding
subjects:
- kind: ServiceAccount
  name: openshift-gitops-argocd-application-controller # O ServiceAccount que será utilizado
  namespace: openshift-gitops # O Namespace onde o ArgoCD está instalado
roleRef:
  kind: ClusterRole
  name: argocd-nmstate-manager # O ClusterRole que criamos anteriormente
  apiGroup: rbac.authorization.k8s.io