apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 03-nmstate-dns-custom
  namespace: openshift-gitops 
spec:
  destination:
    namespace: openshift-nmstate
    name: in-cluster
  source:
    path: openshift-nmstate/03-dns-custom/manifests
    repoURL: https://github.com/marcosraposo/gitops-dns-clean
    targetRevision: HEAD
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
