apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 00-app-of-apps-dns-custom
  namespace: openshift-gitops
  annotations: 
#    argocd.argoproj.io/resource-ignore-errors: |
#      - namespace: openshift-nmstate
#        kind: '*'
#        group: '*'
#        name: '*'
#      - kind: Application #como o job limpa tudo, essa parte pode ocorrer um erro por não ter mais o recurso.
#        name: 03-nmstate-dns-custom      
spec:
  destination:
    namespace: openshift-gitops
    name: in-cluster  
  sources:
    - path: openshift-nmstate/01-operator/
      repoURL: https://github.com/marcosraposo/gitops-dns-clean
      targetRevision: HEAD
    - path: openshift-nmstate/02-instance/
      repoURL: https://github.com/marcosraposo/gitops-dns-clean
      targetRevision: HEAD   
    - path: openshift-nmstate/03-dns-custom/
      repoURL: https://github.com/marcosraposo/gitops-dns-clean
      targetRevision: HEAD          
    - path: openshift-nmstate/04-helper/clean-all-crds
      repoURL: https://github.com/marcosraposo/gitops-dns-clean
      targetRevision: HEAD                
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true   
