apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 00-app-of-apps-dns-custom
  namespace: openshift-gitops
spec:
  destination:
    namespace: openshift-gitops
    name: in-cluster  
  sources:
    - path: openshift-nmstate/01-operator/
      repoURL: https://github.com/marcosraposo/gitops-dns-clean
      targetRevision: HEAD
    - path: openshift-nmstate/02-instance/
      repoURL: https://github.com/marcosraposo/gitops-dns-clean
      targetRevision: HEAD   
    - path: openshift-nmstate/03-dns-custom/
      repoURL: https://github.com/marcosraposo/gitops-dns-clean
      targetRevision: HEAD          
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true   
