apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: nmstate
  namespace: openshift-gitops
spec:
  generators:
  - list:
      elements:
      - appName: operator
        path: application/openshift-nmstate/operator/manifests
      - appName: instance
        path: application/openshift-nmstate/instance/manifests        
      - appName: dns-custom
        path: application/openshift-nmstate/dns-custom/manifests 
  template:
    metadata:
      name: "nmstate-{{appName}}-in-cluster"
    spec:
      project: default
      source:
        repoURL: https://github.com/marcosraposo/gitops-dns-clean
        targetRevision: main
        path: "{{path}}"
      destination:
        name: in-cluster
        namespace: openshift-nmstate
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true          